version: '3.6'
services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=aogeo@csiro-coasts.net"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8081:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  geonetwork:
    container_name: geonetwork
    image: geonetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aogeo.rule=Host(`aogeo.csiro-coasts.net`)"
      - "traefik.http.routers.aogeo.entrypoints=websecure"
      - "traefik.http.routers.aogeo.tls.certresolver=myresolver"
    restart: always
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /var/lib/geonetwork/data
      GEONETWORK_DB_NAME: /var/lib/geonetwork/db/gn
    volumes:
      - geonetwork:/var/lib/geonetwork

volumes:
  geonetwork:
